# Generated by Django 3.0.7 on 2020-06-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commentUser', models.CharField(max_length=150)),
                ('commentMovie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
                ('movieDesc', models.CharField(max_length=250)),
                ('movieRating', models.IntegerField()),
                ('movieGenre', models.CharField(max_length=100)),
                ('movieImg', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=150)),
                ('userPassword', models.CharField(max_length=250)),
            ],
        ),
    ]
